
<!-- Header Starts here -->

<script type="application/ld+json">
    {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Jixi Cloud",
  "url": "https://jixicloud.com/",
  "logo": "https://jixicloud.com/assets/img/logo_main.svg",
  "alternateName": "Jixi Domains",
  "sameAs": [
    "https://www.facebook.com/jixicloud"
  ],
  "contactPoint": [
    {
      "@type": "ContactPoint",
      "telephone": "92573 04118",
      "contactType": "customer service",
      "email": "help@jixicloud.com",
      "areaServed": "IN",
      "availableLanguage": [
        "en",
        "hi"
      ]
    }
  ]
}
</script>
<!--Article Schema Code Generated by Jixi Cloud -->
<link rel="stylesheet" href="{{ asset('style.css') }}">
<script src="https://kit.fontawesome.com/62cca11a06.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="icon" type="image/x-icon" href="/assets/img/favicon.ico">
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YKJHFF7KTM"></script>
<script>
    window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-YKJHFF7KTM');
</script>

<header class="header">
    <nav>


        <div class="logo"><a href="/"><img width="65" style="max-width:90px" src="/assets/img/logo_main.svg"
                    alt="logo"></a></div>
        <div class="gmj-menu">
            <input type="checkbox" id="show-menu">
            <ul class="links">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="#" class="desktop-link">Domains</a>
                    <input type="checkbox" id="show-domains">
                    <label for="show-domains">Domains</label>
                    <ul>
                        <li><a href="/domains/">Registration</a></li>
                        <li><a href="/transfer/">Transfer</a></li>
                    </ul>
                </li>
                <li>
                    <a href="/cloud-hosting/">Cloud Hosting</a>
                </li>

                <li><a href="/support/" class="nav-support btn-primry"><i class="fa-solid fa-headset"></i>Support</a>
                </li>
                <li><a href="/user/login" class="nav-login btn-secondry"><i class="fa-solid fa-user"></i>Login</a></li>
            </ul>
            <label for="show-menu" class="menu-icon"><i class="fas fa-bars"></i></label>
        </div>

    </nav>
</header>



<!-- Header Ends here -->



<!-- Content Section Starts here-->

@yield('mainContent')

<!-- Content Section Ends here-->

<!-- Footer Starts hare -->


 <a href="https://api.whatsapp.com/send/?phone=9188540 37588&text=Hello%20Sir,%20I%20have%20a%20query"
            class="gmj_float right"><span class="my-float"><svg xmlns="http://www.w3.org/2000/svg" fill="#25D366" width="50"
                    height="50" viewBox="0 0 24 24">
                    <path
                        d="M12.031 6.172c-3.181 0-5.767 2.586-5.768 5.766-.001 1.298.38 2.27 1.019 3.287l-.582 2.128 2.182-.573c.978.58 1.911.928 3.145.929 3.178 0 5.767-2.587 5.768-5.766.001-3.187-2.575-5.77-5.764-5.771zm3.392 8.244c-.144.405-.837.774-1.17.824-.299.045-.677.063-1.092-.069-.252-.08-.575-.187-.988-.365-1.739-.751-2.874-2.502-2.961-2.617-.087-.116-.708-.94-.708-1.793s.448-1.273.607-1.446c.159-.173.346-.217.462-.217l.332.006c.106.005.249-.04.39.298.144.347.491 1.2.534 1.287.043.087.072.188.014.304-.058.116-.087.188-.173.289l-.26.304c-.087.086-.177.18-.076.354.101.174.449.741.964 1.201.662.591 1.221.774 1.394.86s.274.072.376-.043c.101-.116.433-.506.549-.68.116-.173.231-.145.39-.087s1.011.477 1.184.564.289.13.332.202c.045.072.045.419-.1.824zm-3.423-14.416c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm.029 18.88c-1.161 0-2.305-.292-3.318-.844l-3.677.964.984-3.595c-.607-1.052-.927-2.246-.926-3.468.001-3.825 3.113-6.937 6.937-6.937 1.856.001 3.598.723 4.907 2.034 1.31 1.311 2.031 3.054 2.03 4.908-.001 3.825-3.113 6.938-6.937 6.938z">
                    </path>
                </svg></span></a>
        <style>
            .gmj_float.right {
                bottom: 50px;
                right: 30px
            }
    
            .gmj_float {
                position: fixed;
                z-index: 999;
                transition: all .3s ease-in-out 0s;
                cursor: pointer;
                outline: none;
                background: #fff;
                border-radius: 50%;
            }
    
            .gmj_float:hover {
                bottom: 55px
            }
        </style>
<div class="gmj-support text-center bg-main mb-1">
    <div class="gmj-container flex">
        <div class="ff-1">
            <div class="ff-left">
                <p class="fsl-1 text-white">
                    <span class="m-block">Need any help? </span>Contact us right now.
                </p>
            </div>
            <div class="ff-right">
                <div class="gmj-btns flex">
                    <a href="https://api.whatsapp.com/send/?phone=9188540 37588&text=Hello%20Sir,%20I%20have%20a%20query"
                        class="btn-primry tawk-button"><i class="fa-brands fa-whatsapp"></i> Live Chat</a>
                    <a href="/user/submitticket" class="btn-secondry"><i class="fas fa-ticket-alt"></i> Support
                        Ticket</a>
                </div>
            </div>
        </div>


    </div>
</div>
<footer class="site-footer bg-secondary no-border">
    <div class="footer-widgets flex">
        <div class="widget">
            <h2 class="widget-title">
                Services
            </h2>
            <ul>
                <li><a href="/domains">Domain Registration</a></li>
                <li><a href="/transfer">Domain Transfer</a></li>
                <li><a href="/cloud-hosting">Cloud Hosting</a></li>
            </ul>
        </div>

        <div class="widget">
            <h2 class="widget-title">
                Company
            </h2>
            <ul>
                <li><a href="/about-us">About Us</a></li>
                <li><a href="/support">Contact Us</a></li>
                <li><a href="/terms">Terms of Service</a></li>
                <li><a href="/privacy">Privacy Policy</a></li>
                <li><a href="/refund">Refund Policy</a></li>
            </ul>
        </div>

        <div class="widget">
            <h2 class="widget-title">
                Useful Links
            </h2>
            <ul>
                <li><a href="/user/submitticket">Submit Ticket</a></li>
                <li><a href="/blog">Read Our Blog</a></li>
            </ul>
        </div>

    </div>
    <div class="footer-bar flex">
        <div class="logo"><img width="50" style="max-width:80px" src="/assets/img/logo_white.svg" alt=""></div>
        <div class="plogos flex">
            <img src="/assets/img/upi.svg" alt="">
            <img src="/assets/img/paypal.svg" alt="">
            <img src="/assets/img/visa.svg" alt="">
            <img class="plm-card" src="/assets/img/master.svg" alt="">
            <img src="/assets/img/dicover1.svg" alt="">
            <img src="/assets/img/rupay.svg" alt="">
        </div>
    </div>
</footer>
<!-- Footer Ends hare -->
